mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.username=tanviply32@gmail.com
mail.password=hozc hmte jujz jsoe
mail.from=tanviply32@gmail.com
